import type { ProgressUpdateRequest } from "@/app/api-service/progressUpdateRequestService";
import { formatEmailDateTime } from "@/app/utils/emailDateTime";

export type ProgressEmailEvent = "SUBMITTED" | "APPROVED" | "REJECTED" | "CANCELLED";

const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] || character);
const percentage = (value: string | number | undefined) => { const parsed = Number(value ?? 0); return Number.isFinite(parsed) ? parsed.toFixed(2) : "0.00"; };

export const progressEmailConfig: Record<ProgressEmailEvent, { title: string; status: string; color: string; pale: string; intro: string; action: string }> = {
  SUBMITTED: { title: "Progress Decrease Approval Request", status: "Pending Approval", color: "#e65100", pale: "#fff3e0", intro: "A progress decrease request is waiting for your review.", action: "Review Progress Request" },
  APPROVED: { title: "Progress Decrease Approved", status: "Approved", color: "#2e7d32", pale: "#edf7ed", intro: "Your requested progress decrease has been approved and applied.", action: "View Progress Request" },
  REJECTED: { title: "Progress Decrease Rejected", status: "Rejected", color: "#c62828", pale: "#fff5f5", intro: "Your requested progress decrease was rejected. The existing progress was retained.", action: "View Progress Request" },
  CANCELLED: { title: "Progress Decrease Request Cancelled", status: "Cancelled", color: "#616161", pale: "#f5f5f5", intro: "The requester cancelled this progress decrease request. Existing progress was unchanged.", action: "View Progress Requests" },
};

export function buildProgressUpdateEmailHTML(event: ProgressEmailEvent, request: ProgressUpdateRequest, recipientName: string, url: string) {
  const style = progressEmailConfig[event];
  const project = request.project?.name || request.context?.projectName || "Project not provided";
  const scope = request.scope?.name || request.context?.scopeName || request.progressLog?.subtask?.task?.scope?.name || "Scope not provided";
  const task = request.task?.title || request.task?.name || request.context?.taskName || request.progressLog?.subtask?.task?.title || "Task not provided";
  const subtask = request.subtask?.title || request.progressLog?.subtask?.title || "Subtask not provided";
  const affectedDate = request.progressLog?.date || request.progressDate || request.entryDate || request.date;
  const eventTime = event === "APPROVED" || event === "REJECTED" ? request.reviewedAt : event === "CANCELLED" ? request.cancelledAt : request.createdAt;
  const eventLabel = event === "SUBMITTED" ? "Submitted At" : `${style.status} At`;
  const rows = [["Project Name", project], ["Scope", scope], ["Task", task], ["Subtask", subtask], ["Affected Progress Date", formatEmailDateTime(affectedDate)], ["Requested By", request.requestedBy?.name || request.requestedBy?.email || "Requester"], ["Requested At", formatEmailDateTime(request.createdAt)], [eventLabel, formatEmailDateTime(eventTime || undefined)]];
  const tableRows = rows.map(([label, value], index) => `<tr style="background:${index % 2 === 0 ? "#f9f6ff" : "#ffffff"}"><td style="padding:11px 16px;border:1px solid #e0e0e0;font-weight:700;color:#0A0A0A;width:38%;font-size:13px">${escapeHtml(label)}</td><td style="padding:11px 16px;border:1px solid #e0e0e0;color:#1a1a1a;font-size:13px">${escapeHtml(value)}</td></tr>`).join("");
  return `<div style="font-family:Arial,sans-serif;background:#f5f5f5;padding:24px;min-height:100%"><div style="max-width:600px;margin:0 auto"><div style="background:#4B2E83;padding:24px 32px;border-radius:8px 8px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:22px;letter-spacing:1px">V.I.S.I.O.N</h1><p style="color:rgba(255,255,255,.75);margin:4px 0 0;font-size:13px">Project Management System</p></div><div style="background:#fff;padding:32px;border-radius:0 0 8px 8px;border:1px solid #e0e0e0;border-top:none"><h2 style="color:#1a1a1a;margin-top:0;font-size:20px">Hey ${escapeHtml(recipientName)},</h2><p style="color:#555;font-size:15px;line-height:1.6">${escapeHtml(style.intro)}</p><div style="background:${style.pale};border-left:4px solid ${style.color};padding:16px 18px;border-radius:4px;margin:20px 0"><span style="background:${style.color};color:#fff;padding:4px 12px;border-radius:20px;font-size:12px;font-weight:700">${escapeHtml(style.status)}</span><p style="margin:14px 0 0;color:${style.color};font-size:24px;font-weight:800">${percentage(request.currentPercent)}% &rarr; ${percentage(request.requestedPercent)}%</p></div><table style="width:100%;border-collapse:collapse;margin:24px 0">${tableRows}</table><div style="background:${style.pale};border-left:4px solid ${style.color};padding:14px 18px;border-radius:4px;margin:20px 0"><p style="margin:0 0 6px;font-weight:700;color:${style.color};font-size:13px">${event === "REJECTED" ? "Reason and Review Feedback" : "Request Details"}</p><p style="margin:0;color:#333;font-size:14px;line-height:1.6"><strong>Request reason:</strong> ${escapeHtml(request.remarks || "—")}${request.reviewRemarks ? `<br><strong>Review remarks:</strong> ${escapeHtml(request.reviewRemarks)}` : ""}</p></div><div style="text-align:center;margin:28px 0 8px"><a href="${escapeHtml(url)}" style="display:inline-block;background:#4B2E83;color:#fff;padding:13px 36px;border-radius:6px;text-decoration:none;font-weight:700;font-size:15px;letter-spacing:.3px">${escapeHtml(style.action)} &rarr;</a></div><p style="color:#999;font-size:12px;text-align:center;margin-top:24px">If the button doesn't work, copy this link:<br><a href="${escapeHtml(url)}" style="color:#4B2E83">${escapeHtml(url)}</a></p></div><p style="text-align:center;color:#bbb;font-size:11px;margin-top:16px">&copy; ${new Date().getFullYear()} V.I.S.I.O.N &middot; Global Visions Holdings Inc.</p></div></div>`;
}
